#ifndef ROBOTGUIDE_COMMUNICATION_APPLICATIONLAYER_PARSER_PARSERSTATE_H
#define ROBOTGUIDE_COMMUNICATION_APPLICATIONLAYER_PARSER_PARSERSTATE_H

namespace robotguide::com::applicationlayer
{
	enum class ParserState
	{
		InstructionType,
		InputType,
		None,
		Error,
	};
}

#endif //ROBOTGUIDE_COMMUNICATION_APPLICATIONLAYER_PARSER_PARSERSTATE_H