#ifndef ROBOTGUIDE_COMMUNICATION_APPLICATIONLAYER_ROUTEREQUEST_H
#define ROBOTGUIDE_COMMUNICATION_APPLICATIONLAYER_ROUTEREQUEST_H

struct routeRequest
{
	int xCurrent;
	int yCurrent;
	int xDestination;
	int yDestination;
};

#endif // !ROBOTGUIDE_COMMUNICATION_APPLICATIONLAYER_ROUTEREQUEST_H

